### ISSUE TITLE
Panic can't be recover in both Then() and ThenAsnyc() function.

### ISSUE THREAD

**Issue by nan-www** [jizhuozhi/go-future#1]
```
func TestThen(t *testing.T) {
	f1 := future.Async(func() (interface{}, error) {
		time.Sleep(1000 * time.Millisecond)
		return "", errors.New("MAGA")
	})
	then := future.Then(f1, func(in interface{}, err error) (interface{}, error) {
		if err != nil {
			panic(err)
		}
		return "success!", nil
	})
	get, err := then.Get()
	if err != nil {
		t.Error(err)
	}
	t.Log(get)
}
```
 Expect to print out error by `t.Error(err)` but panic.

**Comment by jizhuozhi** [comment]
Panic recovering itself is not part of the design of Then and ThenAsync; it is the responsibility of user code. In `go-future`, only `future.Async` implements panic recovering logic, which should not be its responsibility. However, because a new goroutine is created in `future.Async`, if panic in `future.Async` is not recovered, the process will exit unexpectedly. In order To avoid this situation, decide to deal with panic but not responsibility of `go-future`
